site_name: MnMS
site_url: ""
use_directory_urls: false
nav:
    - Home: index.md
    - Code Reference:
        - mnms: reference/SUMMARY.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py  #
  - mkdocstrings:
      watch:
      - src/mnms  #
  - mkdocs-jupyter:
      include: ["*.ipynb"]
#      execute: true
      include_source: True
